// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/user/go-microservices/order-service/internal/domain"
)

// OrderUsecase is an autogenerated mock type for the OrderUsecase type
type OrderUsecase struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, userID, productID, qty
func (_m *OrderUsecase) CreateOrder(ctx context.Context, userID int64, productID int64, qty int) (*domain.Order, error) {
	ret := _m.Called(ctx, userID, productID, qty)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int) (*domain.Order, error)); ok {
		return rf(ctx, userID, productID, qty)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int) *domain.Order); ok {
		r0 = rf(ctx, userID, productID, qty)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, int) error); ok {
		r1 = rf(ctx, userID, productID, qty)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllOrders provides a mock function with given fields: ctx
func (_m *OrderUsecase) GetAllOrders(ctx context.Context) ([]*domain.Order, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllOrders")
	}

	var r0 []*domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Order, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrder provides a mock function with given fields: ctx, id
func (_m *OrderUsecase) GetOrder(ctx context.Context, id int64) (*domain.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderUsecase creates a new instance of OrderUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderUsecase {
	mock := &OrderUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
