// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/user/go-microservices/order-service/internal/domain"
)

// ProductClient is an autogenerated mock type for the ProductClient type
type ProductClient struct {
	mock.Mock
}

// GetProduct provides a mock function with given fields: ctx, id
func (_m *ProductClient) GetProduct(ctx context.Context, id int64) (*domain.ProductView, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *domain.ProductView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.ProductView, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.ProductView); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProductView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReleaseStock provides a mock function with given fields: ctx, id, qty
func (_m *ProductClient) ReleaseStock(ctx context.Context, id int64, qty int) error {
	ret := _m.Called(ctx, id, qty)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) error); ok {
		r0 = rf(ctx, id, qty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReserveStock provides a mock function with given fields: ctx, id, qty
func (_m *ProductClient) ReserveStock(ctx context.Context, id int64, qty int) error {
	ret := _m.Called(ctx, id, qty)

	if len(ret) == 0 {
		panic("no return value specified for ReserveStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) error); ok {
		r0 = rf(ctx, id, qty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductClient creates a new instance of ProductClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductClient {
	mock := &ProductClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
